[package]
name = "wgpu0001"
version = "0.1.0"
edition = "2021"
license = "mit"
authors = ["Philippe Anel"]
repository = "https://github.com/xigh/winit-up-to-date-simple-example"

[dependencies]
winit = "0.29.15"
anyhow = "1.0.81"
